### ISSUE TITLE
ZIP – gestion des background-img: url(...) lors du DL

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#100]
Actuellement ces images là ne sont pas téléchargées

- [x] voir avec badsender si le cas peut se présenter dans le cadre d'un mail : oui, surtout pour les emails responsive
- si oui
  - [x] ~~gérer dans la balise `<style>`~~ sera fait dans #127 
  - [x] gérer l'attribut `style`
  - [x] gérer l'attribut `background`
- MAIS 
  - [x] comment l'utilisateur peut uploader des images “responsives” ?
  - [x] comment uploader dans une background-image ?
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
Dépends de #120

**Comment by Hiswe** [comment]
@Frolipon pour le téléchargement je n'ai pas géré les balises `<style>`. Est-ce utile ?

**Comment by Frolipon** [comment]
Pour ce qui est du style, ce n'est pas indispensable mais si c'est possible, ce serait le premier pas vers de l'affichage mobile (les remplacements d'images en rendu mobile se font via la balise style et des images de background)

**Comment by Hiswe** [comment]
@Frolipon ok il faudra que tu me montres un bout de code pour que je comprenne bien comment ça se passe

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
Je viens de voir que les images de background qui sont dans le tag Outlook ne sont pas en chemin relatif quand on télécharge le zip.
Pour l'image de bg dans la balise <td> on a:
images/img-59521310251b0f000ceb1575-8ee3b831abfc6df4e1e1137aa3bf8c70.jpeg
Dans la balise Outlook on a:
https://badsender-stage.herokuapp.com/img/59521310251b0f000ceb1575-8ee3b831abfc6df4e1e1137aa3bf8c70.jpeg

Il faudrait que le chemin soit en relatif également dans le code Outlook.

**Comment by Hiswe** [comment]
@Frolipon corrigé sur le stage:

https://badsender-stage.herokuapp.com/editor/59521310251b0f000ceb1575

**Comment by Frolipon** [comment]
👍 
Good pour moi en stage
