### ISSUE TITLE
WYSIWYG text bar bug

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#103]
see https://github.com/goodenough/mosaico/issues/7

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon à tester :

https://badsender-test.herokuapp.com/editor/58c14e37b28d40000c8b88a1

**Comment by Frolipon** [comment]
Ça me semble top!

**Comment by Hiswe** [comment]
En stage

**Comment by Frolipon** [comment]
👍

**Comment by Hiswe** [comment]
@Frolipon en prod
