### ISSUE TITLE
Traductions

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#106]
Hello,

Un petit point de traduction qui est encore à faire en fr: le cadre d'insertion de lien qui apparaît quand on met un lien via la barre WYSIWYG:
![image](https://cloud.githubusercontent.com/assets/14838636/23802892/11998428-05b5-11e7-8afa-cb5ffc950313.png)
Insert link --> Insérer un lien
Url --> Url
Text to display --> Texte à afficher
Title --> Titre
Target --> Destination
None --> Aucune
New Window --> Nouvelle fenêtre
Ok --> Ok
Cancel --> Annuler

**Comment by Hiswe** [comment]
En fait c'est tout tinymce qui n'est pas traduit

https://www.tinymce.com/docs/configure/localization/#language_url

**Comment by Hiswe** [comment]
@Frolipon Traductions ajoutées

**Comment by Frolipon** [comment]
Top! Nickel pour moi en test

**Comment by Frolipon** [comment]
Ok pour moi en stage!
