### ISSUE TITLE
Problème image GIF

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#11]
Hello,

Lors de l'utilisation d'une image qui est un GIF animé, le builder semble complètement perdre les pédales, ce qui rend l'import de GIF animé impossible.

Le test peut-être fait avec le GIF animé ci-joint:
![gif_anime_emialing_recette_quinoa](https://cloud.githubusercontent.com/assets/14838636/17207297/3dfd32ec-54b4-11e6-8faf-6ef76fac7b14.gif)
Le problème se pose dans tous les templates, même ceux de Mosaico.

---
- [x] test 2 gifs
- [x] correction du problème
- [x] deploy test
- [x] test badsender
- [x] deploy prod
- [x] test prod badsender

**Comment by Frolipon** [comment]
J'ai trouvé un workaround, j'ai donc redescendu l'urgence d'un niveau. Si je mets le gif à la bonne taille, sans les bords noirs, ça ne pose pas de soucis.
Ça permet de continuer mais le bug reste présent

Voici le gif retravaillé sans les bords noirs:
![gif_anime_emialing_recette_quinoa_2](https://cloud.githubusercontent.com/assets/14838636/17208006/3c29c068-54b7-11e6-80c9-139351549742.gif)

**Comment by Hiswe** [comment]
@Frolipon exemple de test :

https://badsender-test.herokuapp.com/editor/579eff96f823b40300fc4b5f

**Comment by Frolipon** [comment]
Check et ok!
