### ISSUE TITLE
Gallerie template

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#111]
Hello,

Actuellement, la notion de galerie est propre à un email.
Serait-il possible de créer une notion de galerie supplémentaire qui serait propre à un template?

La galerie propre à un email fonctionnerait comme elle fonctionne actuellement
La galerie propre à un template serait une banque d'image commune pour tous les emails venant d'un même template (mais dans un onglet séparé, tout comme il y a actuellement l'onglet "récent" et "galerie" )

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon mis sur le dev

J'ai aussi changé le s3 de *badsender-stage* pour pouvoir tester une fois que l'on passera sur le stage sans impacter la production

**Comment by Frolipon** [comment]
Super! C'est tout à fait ça :-)

Ok pour moi en dev

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
Good en stage!
