### ISSUE TITLE
Génération automatique des images de template

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#113]
Hello,

Est-il possible de faire en sorte que les images des blocks des templates ainsi que l'image principale du template soient générées automatiquement?

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon en test
Vu que l'opération prends du temps, je ne le fais pas automatiquement à chaque upload d'html.
Il faudra cliquer sur le bouton `generate previews` pour mettre à jour.

Il n'y a que la génération des previews de déployé. Pas le composant de background-image

Je te laisse tester.

**Comment by Frolipon** [comment]
J-A-D-O-R-E :-D

Par contre, si je tente par la suite de remettre des images via l'upload d'image, j'ai une 
![image](https://user-images.githubusercontent.com/14838636/27694960-eabaab4e-5ced-11e7-9936-d6243c4c4242.png)

**Comment by Hiswe** [comment]
@Frolipon j'ai des problèmes de timeout sur le stage. Je suis en train d'essayer d'accélérer tout ça.
Je te dirai quand j'aurai mis le stage à jour avec le nouveau code.

Le problème d'upload a déjà été réglé.

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
J'ai toujours le même problème.

Je peux générer des images sur un template qui a déjà des images, mais une fois que je fais ça, si je tente d'uploader des images manuellement, j'ai une Application Error

**Comment by Hiswe** [comment]
@Frolipon Il y avait bien une regression… 
en stage

**Comment by Frolipon** [comment]
Top. Ok pour moi en stage :-)
