### ISSUE TITLE
USER – meilleur gestion de l'activation/reset des comptes

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#114]
- [x] à la réinitialisation d'un mot de passe, l'utilisateur ne doit plus saisir son adresse mail
- [x] l'utilisateur doit confirmer sont mot de passe
- [x] une fois le nouveau mot de passe rentré, l'utilisateur est automatiquement connecté
- [x] un utilisateur dont le mot de passe est réinitialisé est automatiquement déconnecté s'il avait une session d'active

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon il faudrait contrôler les points du ticket :)

**Comment by Frolipon** [comment]
Tout est OK en dev pour moi !

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
Good en stage!
