### ISSUE TITLE
ASSETS – cache-control

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#115]
Allow cache-control to front-end assets for a quicker load of the app

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
### tinymce config

https://www.tinymce.com/docs/configure/integration-and-setup/#cache_suffix
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  cache_suffix: '?v=4.1.6'
});

https://www.tinymce.com/docs/configure/integration-and-setup/#external_plugins
external_plugins: {
    'testing': 'http://www.testing.com/plugin.min.js',
    'maths': 'http://www.maths.com/plugin.min.js'
  }

https://www.tinymce.com/docs/configure/editor-appearance/#skin_url
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  skin_url: '/css/mytinymceskin'
});

https://www.tinymce.com/docs/configure/editor-appearance/#theme_url
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  theme_url: '/mytheme/mytheme.js'
});

https://www.tinymce.com/docs/configure/content-appearance/#content_css
tinyMCE.init({
  selector: 'textarea',  // change this value according to your HTML
  content_css : '/myLayout.css'  // resolved to http://domain.mine/myLayout.css
});

**Comment by Hiswe** [comment]
@Frolipon pas grand chose à vérifier à part que le site fonctionne normalement…

**Comment by Frolipon** [comment]
Il fonctionne normalement :-)

**Comment by Frolipon** [comment]
Idem :-)
