### ISSUE TITLE
IMAGES – faster gif resizing

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#116]
Resizing gif is very slow and memory consuming with *ImageMagick*.

A better solution should be to use *gifsicle*

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon il faudrait vérifier que les gifs s'upload bien.

Malheureusement, on ne pourra voir les statistiques de la console Heroku que sur le stage…

**Comment by Frolipon** [comment]
Ça me semble bon. À noter que le resize des gif ne s'effectue plus que dans 1 seul sens : les gif trop large sont redescendus à la bonne taille.
Les gif pas assez larges ne sont pas resizés. J'image que ça évite des problèmes de perf.

OK en test

**Comment by Hiswe** [comment]
@Frolipon J'ai ouvert un ticket pour l'upscale dans le milestone de ce mois-ci (#123)

**Comment by Frolipon** [comment]
Tout me semble OK!
À noter que le upscale fonctionne déjà en stage. C'est normal?

**Comment by Hiswe** [comment]
@Frolipon en fait il fonctionnait sur la méthode `cover` mais pas sur la méthode `resize`.

**Comment by Frolipon** [comment]
Heu… c'est-à-dire? :-p

**Comment by Hiswe** [comment]
@Frolipon sur mon template de test : 
https://badsender-test.herokuapp.com/editor/5948ea60c90b45000c8e866b 
il y a 2 lignes d'images avec les méthodes de resizing associées :

- **cover** : l'image s'étends dans un cadre pour le remplir, quitte à être coupée
- **resize** : l'image est contenue dans le cadre mais pas coupée

**Comment by Frolipon** [comment]
Ok, je vois.

La question suivante étant:
Faut-il choisir maintenant une des deux méthodes ou bien est-il possible d'en définir une dans le template? Car dans le markup, je ne vois pas comment définir les méthodes

**Comment by Hiswe** [comment]
@Frolipon Je pense que le choix de la méthode se fait par mosaico en fonction des paramètres d'images :

- si hauteur & largeur : cover
- si hauteur OU larger : resize 

C'est comme ça que j'avais configuré pour mon template de test :

https://github.com/goodenough/mosaico/blob/master/templates/sub-themes/template-sub-themes.html#L463-L490
