### ISSUE TITLE
Envoie de mail au rendu cassé sur applications de mails

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#12]
voir https://github.com/goodenough/mosaico/issues/2#issuecomment-235841559
- [x] test avec sendgrid en local
  - [x] envoie sur mail app (MacOs)
  - [x] envoie sur google mail (client web)
- [x] test avec sendgrid en dev
  - [x] envoie sur mail app (MacOs)
  - [x] envoie sur google mail (client web)
  - [x] envoie sur https://www.emailonacid.com (badsender)
- [x] configuration sendgrid en prod 
- [x] test badsender

**Comment by Hiswe** [comment]
Test local (idem sur l'en dev)

Google mail:

![screen shot 2016-08-01 at 15 23 12](https://cloud.githubusercontent.com/assets/96121/17287823/0e5ad828-57fc-11e6-9b63-04e71880a6f6.png)

Mail App

![screen shot 2016-08-01 at 15 23 20](https://cloud.githubusercontent.com/assets/96121/17287831/1ab9c700-57fc-11e6-8209-ff94a03df7d0.png)

**Comment by Hiswe** [comment]
@Frolipon J'ai passé le dev sous https://sendgrid.com/.
Dis moi si cela résoud le problème

**Comment by Frolipon** [comment]
Check et OK!
