### ISSUE TITLE
Warning avant d'écraser une image ans la gallerie

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#122]
Serait-il possible d'ajouter un message de warning de type:

"Une image portant le même nom existe déjà. Souhaitez-vous l'écraser? Oui - Non"
"An image with the same name already exists. Do you wish to overwrite it? Yes - No"

Lorsqu'un utilisateur tente d'uploader une image qui existe déjà dans une galerie?

**Comment by Hiswe** [comment]
Les images sont automatiquement renommées avec des noms unique.

Donc il n'y a pas lieu de faire un warning :)

**Comment by Frolipon** [comment]
Oui, en effet, c'est quelqu'un qui m'a fait ce retour et je n'ai plus pensé au fonctionnement ni testé… Sorry
