### ISSUE TITLE
GIF – not upscaled when smaller than size

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#123]
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon corrigé :

https://badsender-test.herokuapp.com/editor/5948ea60c90b45000c8e866b

**Comment by Frolipon** [comment]
Ok pour moi en test!

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
Ok en stage
