### ISSUE TITLE
Scroll bar pour la gallerie

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#125]
Lorsque la gallerie (email ou template) contient beaucoup d'image, il n'est pas possible de scroller pour aller chercher les images qui sont plus bas.

Il faudrait donc mettre en place une scroll bar

**Comment by Hiswe** [comment]
@Frolipon logiquement c'est déjà fait.

Sur quel navigateur ?

**Comment by Hiswe** [comment]
@Frolipon à tester sur le stage

**Comment by Frolipon** [comment]
Ok en stage!
