### ISSUE TITLE
Error 500 on template link

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#14]
https://badsender-test.herokuapp.com/editor/579eff96f823b40300fc4b5f

```
TypeError: Cannot read property 'mosaico' of null
    at /app/server/creations.js:44:61
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
- [x] reproduce
- [x] patch
- [x] deploy dev
- [x] test badsender
- [x] deploy prod
- [x] test badsender prod

**Comment by Hiswe** [comment]
@Frolipon Une création non trouvée devrait renvoyer maintenant une 404

lien de test :

https://badsender-test.herokuapp.com/editor/579eff96f823b40300fc4b5f

**Comment by Frolipon** [comment]
En prod une création non trouvée renvoie toujours vers une erreur 500.

Exemple:
http://badsender.herokuapp.com/editor/xxxxxxxxxxxxxxxxxxxxxxxx

**Comment by Frolipon** [comment]
J'ai toujours un message d'erreur 500 pour une création non trouvée. Exemple:
https://badsender-test.herokuapp.com/editor/57a0765b24c52303005822fx
ou
https://badsender-test.herokuapp.com/editor/x

La bonne URL étant:
https://badsender-test.herokuapp.com/editor/57a0765b24c52303005822fd

Par contre, si je remplace la dernière lettre non pas par un x mais par un c, là j'ai bien une 404:
https://badsender-test.herokuapp.com/editor/57a0765b24c52303005822fc

J'imagine que cela a à voir avec la validité de l'ID généré.

**Comment by Hiswe** [comment]
@Frolipon Je viens de corriger pour les liens que tu as notés.
À retester sur le dev donc :)

**Comment by Frolipon** [comment]
Check et ok en dev!

**Comment by Hiswe** [comment]
@Frolipon à tester en prod

**Comment by Frolipon** [comment]
Check et OK en prod :-)
