### ISSUE TITLE
comptes sociétés v2 – multiuser

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#18]
La fonctionnalité attendue est la suivante:
1 compte société au sein duquel existent des comptes utilisateurs.
- Les templates de la société sont commun à tous les utilisateurs de la société
- Le super-admin peut créer des utilisateurs pour chaque société
- Pas de password-less connection
- Les créations sont communes à tous les utilisateurs de la société

Remarques de @Hiswe 
- enlever la possibilité pour une société de se connecter
- Un compte société est directement activé
- Quid de création existante ?

--> À voir au cas par cas. Il faudra probablement fusionner certains comptes.

**Comment by Hiswe** [comment]
@Frolipon il y a déjà des comptes utilisateurs qui appartiennent à la même entreprise ?

**Comment by Frolipon** [comment]
Oui, il y a 2 comptes pour SushiShop actuellement (jghodsi@sushishopgroup.com et AKRIEGER@sushishopgroup.com). Ce sont les deux seuls qu'il faudra fusionner. Les autres sont des comptes démo qui doivent rester indépendant les uns des autres.
