### ISSUE TITLE
Unable to use ESP tags

### ISSUE THREAD

**Issue by jloriaux** [goodenough/mosaico#2]
In the generated HTML, special characters are encoded, it is a problem for some of them when we need to use ESP tags.

By example "Hello <% FIRSTNAME %>" is transformed into "Hello `&lt; FIRSTNAME &gt;`" when exported.

---
- [x] Create a simple test case
- ~~Make an automated test~~
- [x] Deploy test server
- [x] Test Badsender
- [x] Deploy prod
- [x] Test Badsender prod

**Comment by Frolipon** [comment]
I would add that the problem appear also in the links, like the code for the mirror web page:
`<a href="&lt;%@ include view='MirrorPageUrl' %&gt;" target="_blank" style="color: #aea18e; text-decoration: underline;">`
when the right link is
`<a href="<%@ include view='MirrorPageUrl' %>" target="_blank" style="color: #aea18e; text-decoration: underline;">`

Strangely, Mosaico seems to convert some characters, like "<", but not other special characters, like "é", "è", …

**Comment by Hiswe** [comment]
EDIT – ceci était la liste des tâches à accomplir

**Comment by Hiswe** [comment]
@Frolipon à contrôler sur :

https://badsender-test.herokuapp.com/admin

##### Url du template de test :

Il faudrait vérifier que le markup de test utilisé comprends bien un ensemble significatif de commentaires et de tags ESP

https://badsender-test.herokuapp.com/users/57710568edb0980300f18e52/wireframe/57947a0f53dff003008488e8

##### Url de la création de test :

Il faudrait contrôler qu'à l'envoie ainsi qu'au téléchargement les commentaires et tags ESP soient bien conservés.

https://badsender-test.herokuapp.com/editor/57947a6253dff003008488e9

##### Pour information

Mettre en place des test automatisés me prendraient trop de temps actuellement… J'ai crée un ticket pour ça ( #9  )

**Comment by Frolipon** [comment]
@Hiswe J'ai fait un test sur base du Mastertemplate de SushiShop que tu peux trouver dans l'environnement de test, et les tags de type <% firstname %> qui sont dans du copy semblent fonctionner correctement à l'export et à l'envoi.

Par contre, les tags qui sont dans des balises lien, de type
`<a href="<%@ include view='MirrorPageUrl' %>">`
ne fonctionnent pas correctement, ils se transforment, à l'export en ceci:
`<a href="https://badsender-test.herokuapp.com/img/576befd6b0623103003f9b4d-<%@ include view='MirrorPageUrl'" %>`
Sur des envois de test, les résultats sont assez farfelus, mais il n'est pas possible de dire si c'est le client email qui s'emmêle les pinceaux avec ce tag qu'il ne comprend pas ou si un autre problème intervient au moment de l'envoi des tests.

**Comment by Hiswe** [comment]
@Frolipon Ok je viens de mettre mon fichier de test.
J'essaie de corriger ça au plus vite…

**Comment by Hiswe** [comment]
@Frolipon Ça devrait être corrigé

**Comment by Frolipon** [comment]
@Hiswe Au niveau du download, tout semble fonctionner correctement. Par contre, au niveau de l'envoi de l'email test, il y a quelque chose qui cloche, comme si la balise <a> avait été virée pour ne garder que le contenu du href. Mais il est difficile de dire ce qu'il se passe exactement, car je ne peux qu'observer le code dans un client email, qui aura déjà mis sa propre couche d'interprétation sur ce qu'il considère comme une balise bizarre.

Voici le rendu de test de l'email envoyé via un test:
https://www.emailonacid.com/app/acidtest/display/summary/eZbI4W5bzo4kXgcHhoHdToUTHDmLFzQczOrscBnLGXOFP/shared

Et le rendu de l'email en faisant un copier/coller du code via le bouton download:
https://www.emailonacid.com/app/acidtest/display/summary/gzPFyYo1kgVg0wR8C6l3iBSCz5nT6Dj0hK74Q1qyNDTqw/shared

**Comment by Hiswe** [comment]
@Frolipon Je n'arrive pas à reproduire dans mon environnement de dev…

**Comment by Frolipon** [comment]
@Hiswe En effet. Le problème vient du relais SMTP a priori. Je t'ai envoyé via Skype des credentials pour utiliser un nouveau relais SMTP qui ne semble pas avoir ce problème

**Comment by Hiswe** [comment]
@Frolipon le serveur de test a été mis à jour avec la nouvelle config

**Comment by Frolipon** [comment]
@Hiswe il y a une modif qui gêne apparemment le builder. Il n'est plus opérationnel en test. Si j'ajoute des blocs, le builder bug complètement. Hors le template utilisé (toujours celui de SushiShop) fonctionnait bien et fonctionne toujours en prod…

Au niveau des envois de test, le problème semble être resté le même par contre…
Il se passe probablement quelque chose au niveau de l'interprétation du code lors de l'envoi au relais SMTP.

**Comment by Hiswe** [comment]
Pour suivi :
- problème des images cassées : résolu dans #13 
- envoies de test : à tester par @Frolipon dans #12

**Comment by Frolipon** [comment]
Tout est nickel 👍
