### ISSUE TITLE
Amélioration listing email

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#21]
Sur la page de listing des emails:
- pagination
- tri
- ~~Sortir le listing des créations dans une page propre (home)~~
- ~~Créer une page de nouvelle création à partir d'un wireframe~~
- filtres (nom,  date de création rechercher)

---
- [x] maquettes
- [x] suppression du bloc “en savoir plus”
- [x] enlever les liens de filtre sur le tableau
- [x] ajouter une croix de suppression des filtres quand filtre actif et fermé
- [x] pagination en 10, 25 et 50
- [x] ajout des fonctionnalités :
  - [x] tri (nom, utilisateur, wireframe, dates)
  - [x] filtres (nom contient, dates de création/update, utilisateurs, wireframes)
- [x] ~~déplacement du logo badsender (en vecto dans le header)~~
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon Voici les designs et interactions que je propose. 

## Maquettes

![badsender-mailing-order](https://cloud.githubusercontent.com/assets/96121/19623852/26e65f8c-9908-11e6-8a9e-254c8eca4187.png)

![badsender-mailing-filter](https://cloud.githubusercontent.com/assets/96121/19623854/2b751908-9908-11e6-9bc6-b0ea776af8c3.png)

![badsender-mailing-filter-active](https://cloud.githubusercontent.com/assets/96121/19623858/38e6e3be-9908-11e6-829d-5324c31102dd.png)

## Interactions

### tri & pagination
- les 5 champs sont triable. 
- Il ne peut y avoir qu'un seul tri actif
- Sur un même champ : un premier click ordonne dans un sens, le second dans le sens opposé, le troisième désactive le tri
- le nombre de lignes par page possible _est à définir_ (10, 25, 50 ?)

### Filtres
- **affichage et application**
  - se déplie en cliquant sur l'icône filtre
  - se replie de la même manière
  - Pour appliquer un filtre, il faudra cliquer sur _appliquer_, fermer le menu ne sera pas suffisant
  - Pour enlever les filtres, click sur _réinitialiser_
  - un résumé s'affiche si un ou plusieurs filtres sont activés.
  - le résumé reste sur une seul ligne et masque le contenu si plus d'une ligne 
- **nom** peut être filtré par un contient
- **Modèles**  selections comme en [démo ici](https://select2.github.io/examples.html#multiple)
-  **Auteurs** 
  - selection identique à **Modèles**
  - Si on clique sur un nom d'utilisateur dans le tableau, le filtre _auteur_ sera remplacé par l'utilisateur
- **Dates** 
  - par défaut la date de fin est le jour-même
  - même type d'interactions que sur [pikaday](https://dbushell.github.io/Pikaday/)

**Comment by Hiswe** [comment]
@Frolipon Pour le logo ça fait très petit si on l'utilise tel quel

J'ai fait quelques screen pour voir si on pouvait alléger ça :

![badsender-logo-full](https://cloud.githubusercontent.com/assets/96121/19756823/72526c6a-9c49-11e6-9c40-e11618795b04.png)

![badsender-logo-cut-with-date](https://cloud.githubusercontent.com/assets/96121/19756827/78f58052-9c49-11e6-8619-32360357968a.png)

![badsender-logo-cut](https://cloud.githubusercontent.com/assets/96121/19756830/80718b96-9c49-11e6-91b7-3afee2ce27a9.png)

**Comment by Hiswe** [comment]
@Frolipon en test

**Comment by Frolipon** [comment]
Tout me semble OK en test.
C'est juste un poil long je trouve quand on passe d'une page à l'autre. Il y a moyen d'optimiser ça?

**Comment by Hiswe** [comment]
@Frolipon On verra pour l'optimisation dans un prochain milestone. Ça ne devrait pas être si lent que ça logiquement pourtant…

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
C'est good pour moi :-)

**Comment by Hiswe** [comment]
@Frolipon en prod. Ticket à fermer si OK.

**Comment by Frolipon** [comment]
Ok pour moi!
