### ISSUE TITLE
Message de confirmation avant supression d'un email

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#22]
Ajouter un message demandant confirmation lors de la suppression d'une création

---
- [x] deploy dev server
- [x] test badsender
- [x] deploy stage server
- [x] test badsender

**Comment by Frolipon** [comment]
Ok pour moi pour monter en stage!

**Comment by Hiswe** [comment]
@Frolipon déployé. À re-tester. Puis si c'est bon, déploiement prod :)

**Comment by Frolipon** [comment]
C'est bon, ça peut monter en prod :-)
