### ISSUE TITLE
Ajout d'un environnement de pre-prod

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#23]
Ajout d'un environnement de pre-prod afin de pouvoir tester les nouvelles fonctionnalités dans un environnement qui utilise déjà les tables de production.

---
- [x] Création du stage
- [x] Création du script de déploiement du stage
- [x] Test badsender (vérification que le stage est identique à la prod)

**Comment by Hiswe** [comment]
@Frolipon Le but serait de ne PAS utiliser la DB de production, ou alors d'en utiliser une copie.

En fait cela permettrait surtout d'avoir un environnement identique entre prod et pre-prod.
Donc les tests effectués sur la pre-prod seraient aussi valides sur la prod, alors qu'actuellement il y a une différence de codes entre dev & prod.

**Comment by Hiswe** [comment]
@Frolipon  à tester https://badsender-stage.herokuapp.com/admin

**Comment by Frolipon** [comment]
Ça semble OK, mais les emails ne sont pas affichés dans le même ordre dans les deux environnements. Normal?
Au niveau de la DB, peut-on imaginer une procédure automatique qui clonerait la DB de prod sur la DB de stage toutes les nuits par exemple? Histoire d'avoir une DB de stage qui est à jour avec la DB de prod sans pour autant faire de l'excès de zèle.

**Comment by Hiswe** [comment]
Concernant la DB, je fais une MaJ avant chaque déploiement du stage. En faire toutes les nuits me semble un peu superflus :)

Pour l'ordre des tableaux, cela ne me semble pas important.
Cela devrait être corrigé avec le #21 

Je me permets de fermer ce ticket
