### ISSUE TITLE
Force redirect to https

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#24]
- [x] forcer le https si option serveur activée
- [x] corriger les urls d'images de mosaico en `edres`
- [x] test dev
- [x] test stage

## pour tester

Toute url en **http** devrait être **redirigée en https**

par exemple : 

- http://badsender-test.herokuapp.com/?page=1 devrait renvoyer vers https://badsender-test.herokuapp.com/?page=1
- http://badsender-test.herokuapp.com/cover/258x100/57c28bf85eeda60a009af548-llama_2.jpg devrait renvoyer vers https://badsender-test.herokuapp.com/cover/258x100/57c28bf85eeda60a009af548-llama_2.jpg

## description du problème 

Quand le site est en https, l'éditeur ne fonctionne plus et/ou mal

```
Failed to load resource: net::ERR_INSECURE_RESPONSE
```

![screen shot 2016-08-02 at 15 16 14 1](https://cloud.githubusercontent.com/assets/96121/17321722/3bfb523a-58c4-11e6-8965-90430bb8e56f.png)

**Comment by Hiswe** [comment]
~~semble fixé par #32~~ finalement non. Bien vérifier que les urls en `edres` utilisent le protocole du navigateur

https://badsender-test.herokuapp.com/editor/57c28bf85eeda60a009af548

Il manquera toutefois de forcer une redirection en https.

**Comment by Frolipon** [comment]
Tout semble OK.
Les URL http redirigent bien vers de l'https

**Comment by Frolipon** [comment]
Good pour moi a priori
