### ISSUE TITLE
HEROKU – enable node concurrency

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#25]
Cela permettra de tirer tout les avantages du scale d'heroku par le futur

https://devcenter.heroku.com/articles/node-concurrency

---
- [x] deploy dev
- [x] test badsender
- [x] deploy stage
- [x] test badsender

**Comment by Hiswe** [comment]
@Frolipon Il ne s'agit donc que de vérifier que le serveur fonctionne :)

**Comment by Frolipon** [comment]
Dans ce cas il fonctionne :-)
Ok pour moi!
