### ISSUE TITLE
HEROKU – custom maintenance/error page

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#26]
Les pages devraient 
- être aux couleurs de badsender
- pouvoir fournir des informations utiles aux utilisateurs.  
  Par exemple, un email ou téléphone de contact

---
- [x] Création de la page d'erreur
- [x] Création de la page de maintenance
- [x] Validation des templates par BS
  - [x] [erreur](https://firebasestorage.googleapis.com/v0/b/badsender-maintenance.appspot.com/o/error.html?alt=media&token=1275ac81-3e8a-4d5c-843b-efb8ca675778) 
  - [x] [maintenance](https://firebasestorage.googleapis.com/v0/b/badsender-maintenance.appspot.com/o/maintenance.html?alt=media&token=98e818d7-e804-4be1-90de-25cc0b26c089)
- [x] Déploiement sur un S3
- [x] Configuration des instances :
  - [x] dev
  - [x] stage
  - [x] production

**Comment by abernier** [comment]
https://devcenter.heroku.com/articles/error-pages

**Comment by Hiswe** [comment]
@Frolipon Je viens de mettre en démo, les 2 pages de maintenance. 

Il faudrait que tu me modifies/valides les contenus (wording, liens…)

Merci d'avance !

**Comment by Frolipon** [comment]
Je valide.
Une seule modif, le lien pour la page de contact en anglais est: http://agency.badsender.com/contact/

**Comment by Hiswe** [comment]
@Frolipon Les urls mises à jour :
- [erreur](https://firebasestorage.googleapis.com/v0/b/badsender-maintenance.appspot.com/o/error.html?alt=media&token=1275ac81-3e8a-4d5c-843b-efb8ca675778) 
- [maintenance](https://firebasestorage.googleapis.com/v0/b/badsender-maintenance.appspot.com/o/maintenance.html?alt=media&token=98e818d7-e804-4be1-90de-25cc0b26c089)

Si c'est bon pour toi, il faudrait que tu les uploads sur votre S3 et que tu me fournisses les urls.
Je pourrais ensuite configurer les applications avec ces pages

**Comment by Frolipon** [comment]
Ok pour moi!
Les url's sont les suivantes:
erreur: `https://s3.eu-central-1.amazonaws.com/builder.badsender.com/maintenance/Badsender+Builder+-+error.htm`
Maintenance: `https://s3.eu-central-1.amazonaws.com/builder.badsender.com/maintenance/Badsender+Builder+-+maintenance.htm`

**Comment by Hiswe** [comment]
@Frolipon 

L'application stage en mode maintenance : https://badsender-stage.herokuapp.com/

Je te laisse le soin de fermer le ticket après vérification

J'enléverai la maintenance après celà

**Comment by Frolipon** [comment]
Je confirme, c'est bon pour moi.
