### ISSUE TITLE
HEROKU – monitoring

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#27]
En vue de maîtrisé les coûts, il serait intéressant de pouvoir surveiller l'application afin de pouvoir optimiser les besoins de ressources de cette dernière

**Comment by abernier** [comment]
https://devcenter.heroku.com/articles/metrics

**Comment by Hiswe** [comment]
Le metrics sont disponibles sur le stage et en prod.
Le test est en dyno “free” et n'a donc pas accès à ces statistiques
