### ISSUE TITLE
HEROKU – alerts

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#28]
Emails should be send when app is down.

https://blog.heroku.com/threshold-alerting-generally-available

**Comment by Frolipon** [comment]
Des emails d'alertes sont désormais configurés.
Par contre, malgré l'augmentation temporaire des capacités serveur sans envoi de nouvelles newsletter, de nombreuses alertes apparaissent quotidiennement. Serait-ce lié à la non optimisation du code ?

**Comment by Hiswe** [comment]
Ça doit être lié au même problème d'url que pour adobe campaign

```
2016-08-25T15:07:43.856869+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/img/?method=resize&params=440%252Cnull&src=%252Fimg%252F57767da32f037e03000a7bd7-tyrsa.jpg" host=builder.badsender.com request_id=9492acb6-a46a-404a-abda-5c0c56bd8bda fwd="109.128.77.12" dyno=web.2 connect=1ms service=30000ms status=503 bytes=0
```

**Comment by Hiswe** [comment]
À vérifier et à fermer le cas échéant

**Comment by Hiswe** [comment]
Les alertes concernent principalement des timeouts sur des gifs animés en GET. Par exemple :

```
/resize/600xnull/57a222d1dd932903001c2c07-GIF_ANIME_EMIALING_RECETTE_QUINOA.gif
/resize/590xnull/587f8a5dbb80c7000c6b53c1-gif_anime_lunchbox_fevrier_fr.gif
```

Il arrive aussi sur des urls de DL en POST. ex :

```
/creations/587f8a5dbb80c7000c6b53c1/zip
```

devrait être résolu avec #41
