### ISSUE TITLE
Import mailing adobe campaign

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#29]
Adobe campaign should be able to download all the assets from a generated mailing
- [x] test sushishop
- [x] correction de l'issue #32
- [x] test Sushishop depuis le dev 
- [x] test avec le client d'un zip avec les caractères spéciaux encodés
- [ ] réponse consultant logs d'erreurs
- [ ] test shushishop depuis la prod suite au déploiement de #32 (meilleur temps de réponse ?)

**Comment by Frolipon** [comment]
Les tests ont été effectué, mais Adobe n'arrive malgré tout pas à récupérer les images.
Plusieurs pistes de solutions:
- Adobe reçoit des erreurs 503, est-il possible de trouver une trace de ces erreurs de notre côté afin de voir si nous avons plus d'info?
- Ci-joint, un fichier de log d'erreur d'une tentative d'import datant du 23/08
  [erreur_caractère_encodé.txt](https://github.com/goodenough/mosaico/files/437275/erreur_caractere_encode.txt)
  [erreur_caractère_non_encodé.txt](https://github.com/goodenough/mosaico/files/437276/erreur_caractere_non_encode.txt)
- Une autre piste par rapport à ce problème pourrait être l'enregistrement des images. Quand on tente d'enregistrer une image du builder, il n'y a pas de nom ni d'extension par défaut (sous Saari et Chrome en tout cas).

Des tests sont envoyés chez le client pour checker si le téléchargement d'un zip avec les images incluses résouts l'ensemble des problèmes.
- [x] tests Sushishop avec un zip image
- [ ] Check des logs d'erreurs
- [ ] Check de l'origine de l'absence de nom et d'extension par défaut et check du temps de la faisabilité et du temps nécessaire pour éventuellement modifier ça

**Comment by Hiswe** [comment]
### extrait du log Adobe Campaign

```
11:56:13 - Echec lors du traitement de la requête HTTP vers l'url 'http://builder.badsender.com/img/?method=resize&params=170%2Cnull&src=%2Fimg%2F57767da32f037e03000a7bd7-packshot_3.jpg'.
11:56:43 - HTTP code=503, <!DOCTYPE html>     <html>     <head>       <meta name="viewport" content="width=device-width, initial-scale=1">       <style type="text/css">         html, body, iframe { margin: 0; padding: 0; height: 100%; }         iframe { display: block; width: 100%;
```

### source du problème

En suivant l'url :

http://builder.badsender.com/img/?method=resize&params=440%252Cnull&src=%252Fimg%252F57767da32f037e03000a7bd7-tyrsa.jpg

On obtient la même réponse que dans le log d'erreur d'Adobe Campaign :

``` html
<html><head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        &lt;p&gt;Application Error&lt;/p&gt;
      </iframe>

    </body></html>
```

![screen shot 2016-08-26 at 15 36 38](https://cloud.githubusercontent.com/assets/96121/17999316/f9f95368-6ba2-11e6-8e5a-fdaa06a9cf90.png)

**Comment by Hiswe** [comment]
Pour suivi :

### Téléchargement

Le téléchargement des images ne fonctionne toujours pas mais on a désormais une erreur différente :

voici les messages d'erreur remonté par le consultant AC:

```
--- Préparation du téléchargement des images ---
Enregistre l'image distante 'https://badsender-test.herokuapp.com/resize/600xnull/57c3ee81c97e9f0a00256153-cover_nl.jpg' localement
Une erreur a interrompu le transfert du fichier 'https://badsender-test.herokuapp.com/resize/600xnull/57c3ee81c97e9f0a00256153-cover_nl.jpg' (-52)
Enregistre l'image distante 'https://badsender-test.herokuapp.com/resize/200xnull/57c3ee81c97e9f0a00256153-packshot_1.jpg' localement
Une erreur a interrompu le transfert du fichier 'https://badsender-test.herokuapp.com/resize/200xnull/57c3ee81c97e9f0a00256153-packshot_1.jpg' (-52)
```

### Download de ZIP

Problème rencontré par le client, c'est que le code HTML est interprété par AC.
@Frolipon Si tu peux me mettre le code interprété par AC ça serait super

Il faudrait être bien sûr que le HTML téléchargé soit encodé en UTF8

https://github.com/expressjs/express/wiki/Migrating%20from%203.x%20to%204.x#rescharset

**Comment by Frolipon** [comment]
Lors du download de ZIP, le problème vient d'une mauvais interprétation des caractères spéciaux:
Exemple: http://t.news.sushishop.fr/nl/jsp/m.jsp?c=%40TXDDCFDA3SRUFSzWDJeoeM870hhlJ0%2FgT6qtN8CRbjQ%3D&utm_campaign=TBD&utm_source=emailing&utm_medium=Actu

L'idée serait donc de mettre en place le ticket #33 en espérant que ça résolve ça.
Première étape: 
- [x] test avec le client d'un zip avec les caractères spéciaux encodés

**Comment by Frolipon** [comment]
Les tests d'un import zip avec caractères spéciaux encodés sont réussis.
Nous allons donc lancer le développement de cette fonction.

Voir ticket #39 

J'attends toujours la réponse concernant les logs afin d'éclaircir cette piste également.

**Comment by Frolipon** [comment]
On m'a soufflé que les logs d'erreurs ne seraient probablement pas facilement disponible. Adobe Campaigns n'étant pas très réactif.
La solution du ZIP fonctionnant bien, nous pouvons donc fermer ce ticket-ci.
