### ISSUE TITLE
IMAGES – refactor url

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#32]
- [x] Modifications à effectuer
  - [x] modification du routing des images _serveur_ & _mosaico_
  - [x] cohabitation avec l'ancien code (1 mois)
  - [x] renommage des images
- [x] test Badsender Dev
- [x] test Badsender Stage
- [x] test Badsender Prod
- [x] déploiement en production coordonné avec Badsender (réupload des images de preview `edres`)

---
### Ce qui est attendu

http://builder.badsender.com/img/?method=resize&params=440%2Cnull&src=%2Fimg%2F57767da32f037e03000a7bd7-video.jpg

devrait être :

http://builder.badsender.com/img/resize/440xnull/2F57767da32f037e03000a7bd7-video.jpg

ainsi que renommer (url friendly) les images uploadées

Bien faire attention au path des images une fois le mailing téléchargé
### Problème actuel relevé

Exemple d'url qui ne fonctionne pas (voir https://github.com/goodenough/mosaico/issues/29#issuecomment-242423623) :

http://builder.badsender.com/img/?method=resize&params=440%252Cnull&src=%252Fimg%252F57767da32f037e03000a7bd7-tyrsa.jpg

Il semble que l'url est encodée 2 fois :

``` js
var url = 'http://builder.badsender.com/img/?method=resize&params=440%252Cnull&src=%252Fimg%252F57767da32f037e03000a7bd7-tyrsa.jpg';
var decodedUrl = decodeURIComponent(url);
```

> http://builder.badsender.com/img/?method=resize&params=440%2Cnull&src=%2Fimg%2F57767da32f037e03000a7bd7-tyrsa.jpg

``` js
var redecodedUrl = decodeURIComponent(decodedUrl);
```

> http://builder.badsender.com/img/?method=resize&params=440,null&src=/img/57767da32f037e03000a7bd7-tyrsa.jpg

**Comment by Hiswe** [comment]
@Frolipon J'ai fait une création de test :

https://badsender-test.herokuapp.com/editor/57c28bf85eeda60a009af548

### A – Pour effectuer ce test :

– télécharger le template sur votre ordinateur
– ouvrir le fichier HTML dans un navigateur
– faire “enregistrer sous” 
– contrôler le dossier d'image associé

### B – Pour comparaison, voici l'ancien comportement :

https://badsender-stage.herokuapp.com/editor/57c28e51d755e20a00b81feb

Répéter la même opération que pour **[A]**

### Résultats attendu :

Les images contenu dans les dossiers devraient avoir les bons noms et les bonnes tailles.

D'après mes essaies : ok pour **[A]**, cassé sur **[B]**

**Comment by Frolipon** [comment]
Go pour le stage!

**Comment by Frolipon** [comment]
Ok pour moi en stage. On va trouver un moment pour se coordonner pour la montée en prod

**Comment by Hiswe** [comment]
Done
