### ISSUE TITLE
MAILING – encode html entities

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#33]
- [x] add he on backend
- [x] don't encode tabs
- [x] test dev

---

https://github.com/mathiasbynens/he

**Comment by Hiswe** [comment]
@Frolipon en dev à tester sur ce mailing et sur d'autres de te choix.

https://badsender-test.herokuapp.com/editor/57c571fed253910a0028e2ff

**Comment by Frolipon** [comment]
Une seule remarque, il faudrait ne pas encoder les tabulations, qui servent en réalité à l'indentation du code:
![image](https://cloud.githubusercontent.com/assets/14838636/18088295/3944ee00-6eba-11e6-8828-9c39556668b4.png)

**Comment by Hiswe** [comment]
@Frolipon fixé

Redéployé sur le dev

**Comment by Frolipon** [comment]
C'est Good en test. Tu peux monter en stage!

**Comment by Frolipon** [comment]
C'est good en test. Tu peux monter en stage!

**Comment by Hiswe** [comment]
@Frolipon du coup je fais un tir groupé avec le zip #39
