### ISSUE TITLE
Nom email téléchargés

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#37]
- [x] nom email
- [ ] ajout de la date

Les email téléchargés devraient avoir pour nom le titre de la création + la date génération

**Comment by Hiswe** [comment]
@Frolipon est-ce qu'avoir juste le nom du mail est suffisant, ou est-ce qu'on veut dans le nom du zip, la date de génération (année-mois-jour:heure-minute) ?

**Comment by Frolipon** [comment]
Pour le moment on va garder ça comme ça. Ce sera peut-être quelque chose qui viendra par la suite, mais il y a d'autres prio avant :-)
