### ISSUE TITLE
MOSAICO – add a download zip 

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#39]
- [x] corriger #33 
- [x] ajout de la fonctionnalité sur mosaico
- [x] test dev
- [x] test stage
- [x] test prod

**Comment by Frolipon** [comment]
@L'objectif de cette fonctionnalité est d'ajouter un bouton à côté du bouton qui permet de télécharger le fichier HTML.

Ce nouveau bouton permettrait de télécharger un fichier ZIP contenant:
- un dossier images avec l'ensemble des images de l'email présentes
- un fichier HTML avec le chemin des images en relatif (donc src="images/monImage.extension")

Un prérequis afin que tout fonctionne correctement est de régler le ticket #33 au préalable

**Comment by abernier** [comment]
@Hiswe pour la génération du zip à partir du html
1. ne pourrait-on pas utiliser un module de scrapping comme https://www.npmjs.com/package/website-scraper ?
2. ou plus simplement télécharger l'ensemble des `<img>` présentes dans la page ?

## 

Pour moi l'avantage du module de scrapping (1.) est que c'est plus ou moins déjà "tout fait", reste plus qu'à zipper... De plus on est sûrs qu'il va effectivement télécharger TOUTES les ressources de la page sans en oublier.

Après si l'on part du principe que seules les balises `<img>` sont à télécharger (ce qui semble être le cas dans un mail : pas de video, pas de JS externe...), peut-être plus vite fait de faire une solution à la mano (2.)...

**Comment by Hiswe** [comment]
Pour info j'avais utilisé [simplecrawler](https://www.npmjs.com/package/simplecrawler) précédemment.

Le problème du crawler étant que je n'ai pas d'url en GET du mailing généré.

**Comment by Hiswe** [comment]
@Frolipon une création de test : 

http://badsender-test.herokuapp.com/editor/57c6af256ea7580a00ce8159

**Comment by Frolipon** [comment]
Une remarque par rapport à la fonctionnalité:
- Les caractères accentués sont désormais transformés en quelque chose de plus exotique. Par exemple, le `é`, qui était en `&eacute;` est désormais `&#xE9;`

**Comment by Frolipon** [comment]
J'ai demandé au client de tester ça, mais avant il m'a signalé un autre problème qui ne semblait pas se produire avant le bouton du ZIP:
Les tags Adobe Campaigns sont cassé:
`<%= recipient.firstName %>` devient `<%= recipient.firstname="" %=""></%=>`

**Comment by Hiswe** [comment]
@Frolipon ok à tester :)

**Comment by Frolipon** [comment]
C'est bon en test! Tout est bon :-). Wouhouuuu
On peut monter en stage!

**Comment by Frolipon** [comment]
Go pour la prod :-)

**Comment by Hiswe** [comment]
@Frolipon en prod. je te laisse fermer le ticket si tout est ok

Est-ce que ça corrige aussi le #29 ?

**Comment by Frolipon** [comment]
C'est good et fermé :-)
