### ISSUE TITLE
IMAGES – cache resized images

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#41]
Logs sans et avec resize :
- connect=0ms service=347ms
- connect=0ms service=2219ms

```
2016-08-30T10:02:01.321301+00:00 heroku[router]: at=info method=GET path="/img/57c5509994f5380a00b3c439-gif_anime_lunchbox_juillet_espagne.gif" host=badsender-stage.herokuapp.com request_id=1ad69608-12fc-4dc4-83cf-a9d6cd28c935 fwd="180.183.159.173" dyno=web.1 connect=0ms service=347ms status=200 bytes=430117
2016-08-30T10:02:21.437061+00:00 heroku[router]: at=info method=GET path="/resize/600xnull/57c5509994f5380a00b3c439-gif_anime_lunchbox_juillet_espagne.gif" host=badsender-stage.herokuapp.com request_id=b62dd7e3-da98-43d0-8c86-163cdfe249f8 fwd="180.183.159.173" dyno=web.1 connect=0ms service=2219ms status=200 bytes=994257
```

–––

edit _2 septembre_

Message d'alerte envoyé par Heroku suite au redimensionnement d'un GIF. 11 secondes…

```
2016-09-01 10:16:51.245
370 <158>1 2016-09-01T10:16:50.807493+00:00 heroku router - - at=info method=GET path="/resize/600xnull/57c7ffd91c4b3e0a005b0784-gif_anime_lunchbox_juillet_espagne.gif" host=badsender-stage.herokuapp.com request_id=230dfc04-d679-43fa-b360-b3ad70d600a8 fwd="109.128.77.12" dyno=web.1 connect=1ms service=11740ms status=200 bytes=994800
```

---

edit _23 septembre_
- [x] ~~ne pas resizer un gif s'il est déjà à la bonne taille~~ #76 
- [x] test dev
- [x] test stage
- [x] controle :
  - [x] cache côté client

**Comment by abernier** [comment]
il n'y a pas un cache des images resizees ? par ex si je demande 2x la meme image ds la meme taille, la 2e fois il ne peut pas directement servir la retaille faite avant ?

**Comment by Hiswe** [comment]
Pas de cache pour l'instant.
Ça peut être une solution, sachant qu'on a uniquement accès à [l'ephemeral file system d'Heroku](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) (donc un cache par dyno)

Il faudrait aussi bien identifier le problèmes :
- savoir si cela vient du fait qu'on stream les images depuis le S3
- savoir si cela vient du redimensionnement. 
  - Dans ce cas on peut aussi tester d'autres librairies : [sharp](https://github.com/lovell/sharp) ou [lwip](https://github.com/EyalAr/lwip)
  - il faudrait aussi tester le coût d'un redimensionnement d'un GIF

**Comment by Hiswe** [comment]
@Frolipon pour tester sur le dev il faudrait juste voir que ça ne casse rien sur l'upload et l'affichage d'image.
On ne pourra malheureusement pas voir l'impact dans les `metrics` de Heroku à cause du fait que nous sommes sur une offre gratuite.

On mesurera plus efficacement l'impact sur le stage et en prod

**Comment by Frolipon** [comment]
Ça ne semble rien casser :-)

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
@Hiswe Je te fais confiance. On verra comment évolue la charge une fois en prod.
