### ISSUE TITLE
COMPANY – clean migration code

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#46]
Suite au #45, il faudra procéder à la suppression du code de migration, ainsi que du code utilisé uniquement dans l'ancien type d'organisation
- [x] nettoyage du code
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon Je viens de finir le nettoyage.

Il faudrait juste vérifier que le site ne plante pas, sur toutes les différentes actions possible.

**Comment by Frolipon** [comment]
Je n'ai remarqué qu'une seule erreur:
En tant qu'admin, quand je tente d'accéder à une création, je tombe sur une page d'erreur:
![image](https://cloud.githubusercontent.com/assets/14838636/18781996/74215234-8184-11e6-96c9-93e57e2abf86.png)

**Comment by Hiswe** [comment]
@Frolipon à tester de nouveau :)

**Comment by Frolipon** [comment]
J'ai re-testé l'ensemble, tout me semble OK :-)

**Comment by Hiswe** [comment]
@Frolipon En stage :)

**Comment by Frolipon** [comment]
Good pour moi en stage!
