### ISSUE TITLE
BACKOFFICE – ajout d'une popup de confirmation pour les suppression

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#47]
Idem à #22 mais pour la partie admin :
- [x] ~~utilisateurs~~ pas possible de supprimer un utilisateur
- [x] wireframes 
- [x] ~~sociétés~~ pas possible de supprimer une société

**Comment by Frolipon** [comment]
Nickel. Serait-il possible de faire la même chose pour un "reset user" ?

**Comment by Frolipon** [comment]
Pour le reset user, nouveau ticket créé:
https://github.com/goodenough/mosaico/issues/112

**Comment by Frolipon** [comment]
Good pour moi!
