### ISSUE TITLE
USER – add a “deactivate mode”

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#48]
Un utilisateur ne doit plus être suprimable, mais désactivable.

En effet, s'il est supprimé les infos de compte seront perdu et les templates qu'il aura crée n'auront plus accès à son nom

- [x] comportement 
  - [x] user désactivable depuis l'admin
  - [x] créations préservées
  - [x] impossible de se connecter sur un user désactivé
- [x] test dev
- [x] test prod

**Comment by Frolipon** [comment]
Ça fonctionne.
Est-il possible d'ajouter un bouton "réactiver"? Je pense au bête cas de figure du "clic sur le mauvais bouton"

**Comment by Hiswe** [comment]
@Frolipon fait

**Comment by Frolipon** [comment]
Ok pour moi!
Pour info, l'ancien mot de passe n'est pas valable (ce qui n'est pas un souci en soi).

**Comment by Frolipon** [comment]
Je viens de recevoir 2 emails de nouveau password.
J'imagine qu'il y en a un qui est parti à ma demande, et un autre qui est parti lors de la réactivation.

**Comment by Hiswe** [comment]
@Frolipon je n'ai pas réussit à reproduire les mails…

Le fait d'activer ou de désactiver un utilisateur n'envoie pas de mail. Mais effectivement le mot de passe de l'utilisateur est réinitialisé à ce moment.

Pour vraiment réactiver un compte il faut :

- cliquer sur `activate`
- cliquer sur `send password mail` et là un mail sera envoyé.

**Comment by Frolipon** [comment]
Ok en stage!
