### ISSUE TITLE
Problème d'overlay dans le picker couleur

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#49]
- [x] test dev
- [x] test stage

---

Hello,

Il semble y avoir un problème d'Overlay dans le picker de couleur du menu de droite sur le builder:
![image](https://cloud.githubusercontent.com/assets/14838636/18248544/28c86886-7379-11e6-83ee-e2a914d9651e.png)

Il semblerait qu'ajouter un attribut `z-index:1000` à la classe CSS  `.mo .evo-pop` résolve le problème.

**Comment by Hiswe** [comment]
@Frolipon Tu pourrais me fournir un template minimum avec un colorpicker ?

**Comment by Hiswe** [comment]
@Frolipon à tester

http://badsender-test.herokuapp.com/editor/57cf9693f40186000a483540

**Comment by Frolipon** [comment]
Ok pour moi en test

**Comment by Hiswe** [comment]
@Frolipon en pre-prod :)

**Comment by Frolipon** [comment]
Good pour monter en prod :-)

**Comment by Hiswe** [comment]
@Frolipon En prod. Je te laisse fermer le ticket
