### ISSUE TITLE
Associer email créé par un admin à un user

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#55]
Il serait utile de pouvoir associer les templates créé par un admin à un user. De manière à pouvoir créer des emails pour un client par exemple.

---

- [x] validation d'une solution
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon Voici la solution proposée

![screen shot 2017-01-17 at 14 51 17](https://cloud.githubusercontent.com/assets/96121/22023011/b85c5156-dcc4-11e6-8896-2d1708f786af.png)

![screen shot 2017-01-17 at 14 51 39](https://cloud.githubusercontent.com/assets/96121/22023019/c0949e00-dcc4-11e6-95fe-692f749b5b78.png)

## notes

- Après transfert ils disparaît forcément de votre liste de mailings
- Le mailing se retrouve facilement accessible depuis la fiche d'un utilisateur.

**Comment by Frolipon** [comment]
Good pour moi!

**Comment by Frolipon** [comment]
Ok pour moi!
