### ISSUE TITLE
TECH – update jade to pug

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#56]
See depreciation warnings on npm install
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon pour tester, il faut juste aller sur les différentes pages du site et voir si ça ne crash pas :)

**Comment by Frolipon** [comment]
Ça ne crash pas :-)

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
Ok en stage

**Comment by Hiswe** [comment]
@Frolipon en prod. Ticket à fermer si OK.

**Comment by Frolipon** [comment]
Ok pour moi!
