### ISSUE TITLE
Update WYSIWYG text bar

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#6]
Hello,

We would like to update the toolbar that appear when we edit a text:
1) We would like to remove the "Headings" and "Blocks" options in the format option:
![image](https://cloud.githubusercontent.com/assets/14838636/16993015/f3f6282e-4ea1-11e6-936d-a38cbd79e9ce.png)

2) We would like to be able to choose more color from the color picker (either on the text color or background text color). Ideally, with to possibilities for the user to either use a more evovlved color picker and a possibility to enter the hexadecimal value for a color.
So instead of this,
![image](https://cloud.githubusercontent.com/assets/14838636/16992403/713ca3c4-4e9f-11e6-89b8-eed9e96710d5.png)
Having something like this:
![image](https://cloud.githubusercontent.com/assets/14838636/16992390/6330b28e-4e9f-11e6-9d9a-465a30ecf201.png)

3) We would like to have the possibility to change the font size in the toolbar.

---
- [x] remove the "Headings" and "Blocks" options in the format option
- [x] choose more color from the color picker (either on the text color or background text color).
- [x] change the font size
- [x] Mettre sur le dev
- [x] Test Badsender
- [x] Deploy prod || voir aussi #15 (changement taille `pt` en `px`)
- [x] test prod badsender

**Comment by Hiswe** [comment]
@Frolipon 
- **Pour le color picker :** tinyMCE ne propose qu'une option “custom” qui amène à un color picker. 
  Il faut à chaque fois repasser par la grille des couleurs.
  Voir [ce codepen](https://www.tinymce.com/docs/demo/full-featured/) pour un exemple de ce à quoi cela ressemblera
- **Pour la liste des tailles de police :** par défaut elles sont de `8pt 10pt 12pt 14pt 18pt 24pt 36pt`. 
  C'est configurable. (voir [ce codepen](https://www.tinymce.com/docs/demo/classic/) pour tester les différentes tailles de police )

**Comment by Hiswe** [comment]
@Frolipon Il me faudrait un test et une validation sur cette fonctionalité

**Comment by Frolipon** [comment]
Check et OK!
