### ISSUE TITLE
ZIP – bug when a same image is used many times

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#61]
Quand on télécharge un zip où une même image est utilisée à plusieurs emplacement, une seule image est disponible dans l'archive.

## pour tester

- ~~https://badsender-test.herokuapp.com/editor/587e4e71720dac000c2c9a1b~~
- https://badsender-test.herokuapp.com/editor/58807e450689d6000c610b24
- téléchargerl'archive
- l'ouvrir : elle devrait contenir 6 images 
  - ornithorynque en gros
  - ornithorynque et lama en medium
  - ornithorynque et lama en petit 
  - un logo BS

### pour mémoire l'archive telle qu'elle était téléchargée avant

[test-download-probleme.zip](https://github.com/goodenough/mosaico/files/711772/test-download-probleme.zip)

**Comment by Frolipon** [comment]
J'ai une 404 quand je tente d'aller sur le lien :-(

**Comment by Hiswe** [comment]
@Frolipon Je sais pas comment je me suis débrouillé :

https://badsender-test.herokuapp.com/editor/58807e450689d6000c610b24

**Comment by Frolipon** [comment]
Ok, je vois bien la différence dans les zip, thanks :-)

**Comment by Frolipon** [comment]
Je ne sais pas trop comment tester ça en stage :-)
