### ISSUE TITLE
Update WYSIWYG text bar interlignage et interlettrage

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#62]
Hello,
Pourrais-tu me donner un estimate du timing qu’il faudrait pour ajouter dans la barre WYSIWYG d’édition de texte une option pour gérer l’interlettrage?

La demande n'est pas encore ferme et dépendra de l'estimate.
- [x] Estimate
- [x] Validation Client
- [x] Test dev
- [x] Test Stage
- [ ] Test Prod

**Comment by Hiswe** [comment]
Ça devrait être assez simple :

http://stackoverflow.com/questions/28205016/how-to-create-a-button-in-tinymce-4-that-increments-letter-spacing-by-1px

**Comment by Frolipon** [comment]
Le client a donné son GO. Donc si ce n'est pas trop compliqué et que tu as l'occasion de l'implémenter dans les prochains jours, ce serait top :-)

**Comment by Frolipon** [comment]
C'est bon pour moi en dev!

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
Ok pour moi en stage!

**Comment by Hiswe** [comment]
@Frolipon en prod. Ticket à fermer si OK.

**Comment by Frolipon** [comment]
Ok pour moi!
