### ISSUE TITLE
ADMIN – improve user form

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#64]
a user form should: 
- show activation process
- provide actions for resetting a user

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon en rouge ce qui a été rajouté.
Pour être cohérent sur la partie admin à chaque présentation d'un utilisateur on affiche ses actions : dans les listings et sur sa fiche.

![screen shot 2017-01-17 at 18 15 00](https://cloud.githubusercontent.com/assets/96121/22031501/12d9f89c-dce1-11e6-95df-02286931a219.png)

**Comment by Frolipon** [comment]
Ok pour moi!

**Comment by Frolipon** [comment]
Ok pour moi!
