### ISSUE TITLE
personnaliser l'objet du test mail

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#67]
Possibilité de personnaliser l'objet du test email lors de l'envoi d'un email de test.
Par défaut, serait-il possible de mettre le nom nom de l'email plutôt que ce qu'il y a actuellement?

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
Oui ça devrait être possible.
Même nom que le sur le téléchargement d'un zip ?

**Comment by Hiswe** [comment]
@Frolipon ce qui sera fait :

- un préfixe configurable (défault : *[badsender email builder]*)
- le nom du mail

example : `[badsender email builder] newsletter 71`

**Comment by Frolipon** [comment]
Ok pour moi en dev!

**Comment by Frolipon** [comment]
Good.
À noter que si on dégomme le nom d'une créa existante via l'interface wysiwyg, le nom devient "NO NAME", mais c'est l'ancien nom (celui qui a été dégommé), qui reste enregistré et qui sert d'objet.
Ce comportement me semble parfaitement OK, juste être certain que c'est bien comme ça que c'est voulu :-)

**Comment by Frolipon** [comment]
À voir avec le ticket https://github.com/goodenough/mosaico/issues/83 du coup
