### ISSUE TITLE
Possibilité de personnaliser l'expéditeur et le reply-to

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#68]
Possibilité de personnaliser l'expéditeur du test email lors de l'envoi d'un email de test ainsi que le reply-to.
Éventuellement le faire au niveau société si c'est compliqué à gérer pour chaque envoi de test.

---

- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
Pour l'expéditeur, ça serait bien de garder le même nom de domains qu'actuellement.
Il peut y avoir des problèmes si l'utilisateur rentre certaines adresses (voir [dmarc](https://sendgrid.com/blog/yahoo-dmarc-update/))

Pour le reply-to on peut le mettre directement sur l'adresse mail de l'utilisateur ?
Ou alors avoir une adresse globale pour la société.
Cela éviterait de devoir passer par un prompt custom, en lieu et place de celui du navigateur.

**Comment by Frolipon** [comment]
Expéditeur, d'accord avec toi.

Pour le reply-to, on va le passer sur l'adresse de l'utilisateur

**Comment by Hiswe** [comment]
@Frolipon À tester :) ainsi que tout les tickets qui te sont assignés !

**Comment by Frolipon** [comment]
Ok pour moi en dev!

**Comment by Frolipon** [comment]
Ok pour moi!
