### ISSUE TITLE
WYSIWYG text bar bug

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#7]
Sometimes the text bar stays on the screen even when we click somewhere else and scroll elsewhere.

Issue can sometimes be reproduced by
1) click in an editable text
2) click on another block (but not an element in a block)

This issue can be marked as low prio

---
- [x] Find a way to always reproduce
- [x] patch
- [x] deploy dev
- [x] test badsender dev
- [x] deploy prod
- [x] test badsender prod

**Comment by Hiswe** [comment]
- make a long creation until scrolls appear
- click on the top most text-editable block -> controls appear
- scroll down and select the bottom most block
- unselect it
- scroll up -> text controls will appears again

**Comment by Hiswe** [comment]
@Frolipon dans mon [commentaire précédent](https://github.com/goodenough/mosaico/issues/7#issuecomment-236853305) c'est la seule façon que j'avais trouvé pour reproduire (donc un problème qui apparaissait au scroll).

Dis moi s'il y en a d'autres :)

**Comment by Frolipon** [comment]
Check et OK en dev :-)

**Comment by Hiswe** [comment]
À tester en prod

**Comment by Frolipon** [comment]
Check et OK en prod :-)

**Comment by Frolipon** [comment]
Hello,

J'exhume ce ticket car le bug semble revenu en prod.

**Comment by Hiswe** [comment]
duplicated in #103
