### ISSUE TITLE
Tags in creations

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#70]
- [x] ajout de tags sur une création
  - [x] ajout de la donnée
  - [x] ajout d'une UX
  - [x] filtres par tags
- [x] test dev
- [x] test stage

---

Quelques précisions :

- Un tag (ou label) est un texte qui peut contenir tout caractères sauf `"` et `,`
- Pour supprimer un tag il faut qu'aucun mailing ne porte le tag en question

**Comment by Hiswe** [comment]
Voilà à quoi ça devrait ressembler.

Pour l'instant on ne pourra pas supprimer/renommer un tag.

@Frolipon bon pour toi ?

![00-badsender-mailing-line-no-selection](https://cloud.githubusercontent.com/assets/96121/20703808/750f8e22-b61d-11e6-8ff3-362b74bfd5e3.jpg)

![01-badsender-mailing-line-selection](https://cloud.githubusercontent.com/assets/96121/20703809/752f80e2-b61d-11e6-81ea-70158111d501.jpg)

![02-badsender-mailing-line-selection](https://cloud.githubusercontent.com/assets/96121/20703810/753f3172-b61d-11e6-8178-c3bc405089b6.jpg)

![03-badsender-mailing-line-selected](https://cloud.githubusercontent.com/assets/96121/20703811/7545bed4-b61d-11e6-9f26-20bbec0742d1.jpg)

![04-badsender-mailing-filter](https://cloud.githubusercontent.com/assets/96121/20703812/754b8cf6-b61d-11e6-9272-0654b304f232.jpg)

**Comment by Frolipon** [comment]
Yep, c'est nickel :-)

**Comment by Frolipon** [comment]
Alors, fonctionnellement, ça me semble bien, mais quelques petits points:
- transformer le curseur de la souris en pointeur au survol des tags:
![image](https://cloud.githubusercontent.com/assets/14838636/21519119/24b499c4-cceb-11e6-8ca1-62a3a966a644.png)
- Il faut prévoir un scroll pour faire défiler les tags lorsqu'ils sont nombreux
![image](https://cloud.githubusercontent.com/assets/14838636/21519198/93d8e9a4-cceb-11e6-810a-dde9a4174446.png)
-Dans la dernière capture, j'ai créé 2 tags avec le même nom (test4), et ça me créé un tag sans checkbox. Idem si je créé "test 1" et "test,1", vu que la virgule est un caractère interdit et se transforme en espace

**Comment by Hiswe** [comment]
@Frolipon ça devrait être corrigé

**Comment by Frolipon** [comment]
Good pour moi :-)

**Comment by Frolipon** [comment]
Je vois un point que je n'avais pas vu précédemment:
S'il y a trop de tags, ou si les tags sont trop long, l'affichage explose. Possible de faire passer à la ligne?
![image](https://cloud.githubusercontent.com/assets/14838636/21846563/fa63d7ee-d7f7-11e6-8bce-fa11e812beee.png)

**Comment by Hiswe** [comment]
@Frolipon Ça devrait être ok

**Comment by Frolipon** [comment]
Ok pour moi :-)
