### ISSUE TITLE
LOGO BADSENDER

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#72]
À la suite de #21, le logo badsender est absent du site.

Il faudrait peut être le rajouter quelque part :)

@Frolipon à toi de me dire ce qu'il en est, ou de fermer le ticket si tu estimes que ça ne servirait à rien.

**Comment by Frolipon** [comment]
En effet, ce serait bien de le rajouter.
Possible pour toi de l'ajouter en haut à droite, à côté du nom?
![image](https://cloud.githubusercontent.com/assets/14838636/21519942/0626e754-ccf1-11e6-833d-081433f1661b.png)
Le logo est disponible ici:
.ai : https://www.dropbox.com/s/2paan7nhex9m92l/logo_badsender_white.ai?dl=0
.eps : https://www.dropbox.com/s/i6klhu9wnwh6oc4/logo_badsender_white.eps?dl=0
.png : https://www.dropbox.com/s/o6jq20yepk0p875/logo_badsender_white_350x270.png?dl=0

**Comment by Frolipon** [comment]
Ok en dev!

**Comment by Frolipon** [comment]
Ok en stage!
