### ISSUE TITLE
HOME – suppression de multiples mailings

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#78]
- [x] test dev
- [x] test stage

**Comment by Frolipon** [comment]
Tout semble bien fonctionner.
Il faudrait juste updater le message de warning qui dit "This will remove"
Il faut soit ajouter la liste des éléments qui seront supprimés, soit terminer la phrase par "This will remove n item(s)"

**Comment by Hiswe** [comment]
@Frolipon Ça devrait être corrigé.

**Comment by Frolipon** [comment]
Yep, c'est tout bon pour moi!

**Comment by Frolipon** [comment]
Good pour moi
