### ISSUE TITLE
Email name edition

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#8]
Hello,

We would like to be able to edit the email name not only in the home page but also on the email creation page 

---
- [x] Show actual creation name in the editor
- [x] On double click, convert to input
- [x] On ok (button)
  - [x] save to DB
  - [x] revert to plain text
- [x] On cancel (button) 
  - [x] revert to previous name
  - [x] revert to plain text
- [x] deploy on dev
- [x] badsender validation
- [x] deploy on prod
- [x] test prod badsender

**Comment by Hiswe** [comment]
- [ ] Show actual creation name in the editor
- [ ] On double click, convert to input
- [ ] On ok (button)
   - [ ] save to DB
   - [ ] revert to plain text
- [ ] On cancel (button) 
   - [ ] revert to previous name
   - [ ] revert to plain text
- [ ] deploy on dev
- [ ] badsender validation
- [ ] deploy on prod

**Comment by Hiswe** [comment]
@Frolipon Il me faudrait le test de la fonctionnalité.

Merci d'avance :)

**Comment by Frolipon** [comment]
Ok pour moi :-)

**Comment by Frolipon** [comment]
Check et ok!
