### ISSUE TITLE
IMAGES – resized images don't send a 404 if not founded

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#80]
Finish in timeout  :S

- [x] test dev
- [x] test stage

## pour tester

urls qui devraient renvoyer des 404 :

- http://badsender-test.herokuapp.com/img/57c28bf85eeda60a009af548-llama.jpg
- http://badsender-test.herokuapp.com/resize/285x180/57c28bf85eeda60a009af548-llama.jpg
- http://badsender-test.herokuapp.com/cover/285x180/57c28bf85eeda60a009af548-llama.jpg

urls qui fonctionnent :

- http://badsender-test.herokuapp.com/img/57c28bf85eeda60a009af548-llama_2.jpg
- http://badsender-test.herokuapp.com/resize/285x180/57c28bf85eeda60a009af548-llama_2.jpg
- http://badsender-test.herokuapp.com/cover/285x180/57c28bf85eeda60a009af548-llama_2.jpg

**Comment by Frolipon** [comment]
Ok pour moi en dev!

**Comment by Frolipon** [comment]
Good pour moi,

testé avec
https://badsender-stage.herokuapp.com/cover/150x150/5836eb58901905000c89455e-004brandalley_03_image.jpg

et
https://badsender-stage.herokuapp.com/cover/150x150/5836eb58901905000c89455e-004brandalley_0399_image.jpg

**Comment by Hiswe** [comment]
@Frolipon Sympa tes photos de vacance
