### ISSUE TITLE
Choix de taille de typo dans la barre WYSIWYG

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#81]
Hello,

Ce serait pas mal d'étoffer le choix des tailles de typo disponible dans la barre WYSIWYG, pour au moins avoir l'ensemble de ces tailles de typo-ci en px:
8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|27|28|29|30|31

Le top du top, si possible, serait de pouvoir entrer une taille de typo manuellement!

---

- [x] validation d'une solution
- [x] règles de validations
  - [x] enlever la select
  - [x] taille mini : 8
  - [x] taille maxi : aucune
  - [x] pas de décimales
  - [x] ~~essayer de voir si possibilité de faire un message d'erreur de validation dans mosaico~~ possible dans tinyMCE mais pas satisfaisant
- [x] test dev
- [x] test stage

**Comment by Hiswe** [comment]
@Frolipon Je viens de déployer sur le serveur de test un prototype de ce que ça pourrait donner avec un champ libre

![screen shot 2017-01-12 at 17 05 09](https://cloud.githubusercontent.com/assets/96121/21899048/26c595f0-d8ef-11e6-8cbc-417c999309ef.png)

Il faut :

-  cliquer sur ce qui est entouré en rouge
- rentrer un chiffre (pas de contrôles pour l'instant)

À voir si tu trouves cela mieux qu'une énorme liste de tailles, et à ta disposition pour en discuter.

**Comment by Frolipon** [comment]
C'est nickel!
Effectivement, juste faire un check sur une entrée de chiffre entier (pas de décimale), et alors on peut même dégommer l'autre option juste à droite.

**Comment by Hiswe** [comment]
@Frolipon à tester dans sa version finale.
Je n'ai pas mis de messages d'erreurs si l'utilisateur rentre une valeur erronnée.

**Comment by Frolipon** [comment]
Ok pour moi!

**Comment by Frolipon** [comment]
Good pour moi!

**Comment by Frolipon** [comment]
Yop, je viens de remarquer un truc.
Quand on utilise une taille de police définie, la barre WYSIWYG s'allonge, et on n'a plus accès au bouton d'édition de code tout à fait à droite de la barre:
![image](https://cloud.githubusercontent.com/assets/14838636/22374137/2fd1c602-e4a5-11e6-86a8-29328e7771b3.png)
![image](https://cloud.githubusercontent.com/assets/14838636/22374145/39c40c06-e4a5-11e6-8666-875cc8e97f15.png)

**Comment by Hiswe** [comment]
@Frolipon corrigé sur le stage

**Comment by Frolipon** [comment]
Top! C'est good.

**Comment by Hiswe** [comment]
en prod
