### ISSUE TITLE
Problème de nom

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#83]
si on dégomme le nom d'une créa existante via l'interface wysiwyg, le nom devient "NO NAME", mais c'est l'ancien nom (celui qui a été dégommé), qui reste enregistré et qui sert d'objet.

**Comment by Hiswe** [comment]
@Frolipon Ok ça devrait être corrigé.

Je force dont une création à avoir un nom selon la langue choisie ( `untitled` ou `sans titre`  )
Je ne sais pas pourquoi je n'avais pas forcé le champ lors de la mise en place des tris ou filtres…

J'ai crée des tickets sur janvier pour être sûrs qu'on n'ait plus ce genre de problème ( #84 &  #85)

**Comment by Frolipon** [comment]
Top!
