### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#9]
Functional tests should be provided to avoid any regression as the application grow.
- https://github.com/theintern/intern
- https://www.npmjs.com/package/nightmare

**Comment by abernier** [comment]
Mon retour d'exp là dessus, ma stack utilisée sur [upup-www](https://github.com/abernier/upup-www/blob/master/test/index.js#L390) :
- [wd](https://github.com/admc/wd) comme driver selenium
- [tap](https://github.com/tapjs/node-tap) comme "framework minimal" de test

Tourne notamment en local avant de pouvoir s'executer sur une ferme selenium distante type browserstack
