### ISSUE TITLE
ADMIN – change wording on wireframes

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#94]
changer `wireframes` => `templates`

- [x] test dev
- [x] test stage

**Comment by abernier** [comment]
idem pour `mailing`/`creation` ;)

**Comment by Frolipon** [comment]
Hello,

Il reste encore des occurrences:
![image](https://cloud.githubusercontent.com/assets/14838636/23749561/1f425b46-04c9-11e7-8b67-913a1f0f9aa3.png)
Idem pour le FR: tu peux remplacer "modèle" par "template"

**Comment by Hiswe** [comment]
@Frolipon Je me suis permis de mettre ça en stage.

**Comment by Frolipon** [comment]
Ok pour moi!
