### ISSUE TITLE
IMAGES – faster resizing

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#96]
Pour toute autre image qu'un gif animé il serait préférable d'utiliser sharp à la place d'imageMagic

http://sharp.dimens.io/en/stable/performance/

**Comment by abernier** [comment]
:+1:

**Comment by Hiswe** [comment]
@Frolipon il faut juste contrôler que toutes sortes d'images puissent êtres uploadées sans que ça ne casse rien…

**Comment by Frolipon** [comment]
Ça semble Ok pour moi. Testé avec png, jpg et gif

**Comment by Hiswe** [comment]
@Frolipon en stage

**Comment by Frolipon** [comment]
L'import des GIF ne fonctionne pas sur le stage :-/
J'ai soit ça:
![image](https://cloud.githubusercontent.com/assets/14838636/24949885/68afdfea-1f6f-11e7-8abe-c3eaa0db031a.png)

Soit un message d'erreur car le fichier est trop gros (j'ai tenté ma chance avec un gif de 1,9mo aussi, ce qui est totalement contraire aux bonnes pratiques)

**Comment by Hiswe** [comment]
@Frolipon effectivement il y a avait un bug sur le stage.
J'ai poussé le code du dev en stage, à priori il n'y plus le problème.

Pour ce qui est de la popup d'erreur pour la limite de taille c'est normal, elle est fixée à environ 1Mb

**Comment by Frolipon** [comment]
J'ai encore des bugs. Le chargement est assez long pour des gif (même très léger), et au 3ème gif que j'ai tenté de pousser, il me met le message d'erreur suivant:
![image](https://cloud.githubusercontent.com/assets/14838636/25891363/15e4a9a4-3571-11e7-9e8d-c7084075422a.png)
Les metrics sur le stage semblent d'ailleurs avoir explosées.

J'ai tenté avant ça de charger des gif beaucoup trop lourd (plus de 1mo) avec le message d'erreur attendu comme quoi l'image était trop grosse.

Sinon, les gif chargés auparavant ne dépassaient pas 200ko

**Comment by Hiswe** [comment]
@Frolipon Il y avait bien un bug avec les images dont l'extension est en majuscule.
C'est corrigé. Le site accepte les majuscules ou sans.

Tu pourrais retester ?

**Comment by Hiswe** [comment]
@Frolipon Pour ce qui est du temps de redimensionnement il y a un ticket d'ouvert ( #116  ) qui devrait améliorer les choses

**Comment by Frolipon** [comment]
Tout me semble bon :-)
