### ISSUE TITLE
Bug font-size

### ISSUE THREAD

**Issue by Frolipon** [goodenough/mosaico#97]
J'ai un template ou la font-size des titres est, par défaut, à 34px. Or quand je charge ce template la font-size par défaut passe à 8px.
En testant, il semble qu'une font-size supérieure ou égale à 32px soit overridée par une font-size de 8px.

Le template en question:

[20170127_mastertemplate_ELLE.html.zip](https://github.com/goodenough/mosaico/files/771071/20170127_mastertemplate_ELLE.html.zip)

La ligne contnant la font-size est la ligne 799

**Comment by Hiswe** [comment]
À mon avis cela vient du fait que dans le template la select est définie entre 8 et 31 et que tu essaies de l'initialiser à 40.

```
size { label: Taille; widget: select; options: 8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|27|28|29|30|31; }
```

À fermer si ça vient bien de là

**Comment by Frolipon** [comment]
C'était bien ça, merci :-)
