### ISSUE TITLE
IMAGES – cache-control & image reupload

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico#98]
Pour l'instant on a mis en place un cache côté navigateur d'un jour.
Le cas qui n'est pas géré étant celui de l'utilisateur re-uploadant une image du même nom mais au contenu différent.

**Comment by Hiswe** [comment]
@Frolipon pour contrôler uploader deux images différentes qui ont le même nom.
Les deux doivent apparaître différentes tout simplement

**Comment by Hiswe** [comment]
@Frolipon oups un problème non résolu avec les previews des blocs

**Comment by Hiswe** [comment]
@Frolipon cette fois c'est bon, voir https://github.com/goodenough/mosaico/issues/98#issuecomment-286957357 pour comment tester, à la fois pour les images uploadées dans un mailing ou les images du template

**Comment by Frolipon** [comment]
Si je mets une image 1 qui a le même nom qu'une image deux dans des blocs images différents, pas de soucis.
Par contre, si je tente d'écraser un bloc qui a une image 1 avec une image 2 qui a le même nom, cela ne fonctionne plus.

De plus, après avoir fait quelques essais, cela ne fonctionne plus du tout :-/

**Comment by Hiswe** [comment]
@Frolipon je viens d'essayer et je n'arrive pas à reproduire. 
Il faudrait qu'on fasse un skype tout le deux pour un pas à pas

**Comment by Frolipon** [comment]
Restesté en stage, et tout fonctionne :-)

Je me suis peut-être raté dans les tests :-p
